// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yohyxkdxwhegurcmxlci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvaHl4a2R4d2hlZ3VyY214bGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDU2OTAsImV4cCI6MjA3MTI4MTY5MH0.gyLbQAxEx1W3Ds6OD6i76ieAB_7eMUo6A3iVCyk3gEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});